# -*- coding: utf-8 -*-
"""whole.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C8zn2CTnyW5X6L_nHvhhVLKAj3nxnDve
"""

from google.colab import drive
drive.mount('/content/drive')

path1 = '/content/drive/MyDrive/reshift estimation dataset/cropped_dataset_32x32.h5'
path2 = '/content/drive/MyDrive/reshift estimation dataset/new_dataset64x64.hdf5'

import h5py
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from tensorflow.keras import layers , models, datasets, Input
from sklearn.model_selection import train_test_split
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

with h5py.File(path1 , 'r') as hf:
    images = np.array(hf['images'])
    redshifts = np.array(hf['specz_redshift'])
    redshift_err = np.array(hf['specz_redshift_err'])

#plotting histogram of redshift values befoe normalization

plt.figure(figsize=(10, 5))
plt.hist(redshifts, bins=100, alpha=0.6, label="Histogram")
plt.title("Histogram of Redshift Values")
plt.xlabel("Redshift")
plt.ylabel("Density")
plt.show()

# From (samples, channels, height, width) to (samples, height, width, channels)
images = np.transpose(images, (0, 2, 3, 1))



images = images / 255
# redshifts = (redshifts - redshifts.min()) /(redshifts.max() - redshifts.min())
scalar = MinMaxScaler()

X_train , X_test, y_train , y_test = train_test_split(images , redshifts, test_size = 0.2 ,random_state = 42)
#  = train_test_split(redshifts , test_size = 0.2 ,random_state = 42)

y_train = scalar.fit_transform(y_train.reshape(-1, 1))

# Reshape y_train and y_val to have an explicit shape of (num_samples, 1)
y_train = y_train.reshape(-1, 1)
# y_val = y_val.reshape(-1, 1)

early_stopping = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)
model_checkpoint = ModelCheckpoint('best_model.keras', monitor='val_loss', save_best_only=True)



inputs = tf.keras.Input(shape=(32, 32, 5))  # Input layer

x = tf.keras.layers.Conv2D(32, (5, 5), activation='relu')(inputs)
x = tf.keras.layers.MaxPooling2D(pool_size=(2, 2))(x)
x = tf.keras.layers.Conv2D(64, (5, 5), activation='relu')(x)
x = tf.keras.layers.MaxPooling2D(pool_size=(2, 2))(x)
x = tf.keras.layers.Flatten()(x)
x = tf.keras.layers.Dense(220, activation='relu')(x)
x = tf.keras.layers.Dropout(0.5)(x)
x = tf.keras.layers.Dense(64, activation='relu')(x)
x = tf.keras.layers.Dropout(0.5)(x)
outputs = tf.keras.layers.Dense(1, activation='sigmoid')(x)

model = tf.keras.Model(inputs=inputs, outputs=outputs)

model = models.Model(inputs=inputs, outputs=outputs)
model.compile(optimizer = 'adam' , loss = 'mean_squared_error' , metrics = ['mae'])
model.summary()

# model.summary()
history = model.fit(
    X_train, y_train,
    epochs=50,
    validation_split = 0.3,
    batch_size=156,
    callbacks=[early_stopping, model_checkpoint]
)

import matplotlib.pyplot as plt

# Function to plot training history
def plot_training_history(history):
    plt.figure(figsize=(12, 6))

    # Plot loss
    plt.subplot(1, 2, 1)
    plt.plot(history.history['loss'], label='Training Loss')
    plt.plot(history.history['val_loss'], label='Validation Loss')
    plt.title('Model Loss (MSE)')
    plt.ylabel('Loss (MSE)')
    plt.xlabel('Epoch')
    plt.legend(loc='upper right')

    # Plot MAE
    plt.subplot(1, 2, 2)
    plt.plot(history.history['mae'], label='Training MAE')
    plt.plot(history.history['val_mae'], label='Validation MAE')
    plt.title('Model MAE')
    plt.ylabel('Mean Absolute Error')
    plt.xlabel('Epoch')
    plt.legend(loc='upper right')

    plt.tight_layout()
    plt.show()

# Call the function after training completes
plot_training_history(history)

# Generate predictions on the validation set
y_tr_pred = scalar.inverse_transform(model.predict(X_train))

# Plot the actual vs predicted redshift
plt.figure(figsize=(6, 6))
plt.scatter(scalar.inverse_transform(y_train), y_tr_pred, alpha=0.5, color='b')  # Scatter plot for actual vs predicted redshifts
plt.plot([0, 0.25], [0, 0.25], 'r--')  # Plot a reference line for perfect predictions
plt.title('Actual vs Predicted Redshift')
plt.xlabel('Actual Redshift')
plt.ylabel('Predicted Redshift')
plt.show()

correlation_coefficient = np.corrcoef(scalar.inverse_transform(y_train).flatten(), y_tr_pred.flatten())[0, 1]
print(f"Correlation Coefficient (train): {correlation_coefficient}")

# Generate predictions on the validation set
y_ts_pred = scalar.inverse_transform(model.predict(X_test))

# Plot the actual vs predicted redshift
plt.figure(figsize=(6, 6))
plt.scatter(y_test, y_ts_pred, alpha=0.5, color='b')  # Scatter plot for actual vs predicted redshifts
plt.plot([0, 0.25], [0, 0.25], 'r--')  # Plot a reference line for perfect predictions
plt.title('Actual vs Predicted Redshift')
plt.xlabel('Actual Redshift')
plt.ylabel('Predicted Redshift')
plt.show()

correlation_coefficient = np.corrcoef(y_test.flatten(), y_ts_pred.flatten())[0, 1]
print(f"Correlation Coefficient (test): {correlation_coefficient}")